
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from Client import EmailClient
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, messagebox


OUTPUT_PATH1 = Path(__file__).parent
ASSETS_PATH1 = OUTPUT_PATH1 / Path(r"Page1.3\assets\frame0")

OUTPUT_PATH2 = Path(__file__).parent
ASSETS_PATH2 = OUTPUT_PATH2 / Path(r"Page2.1\assets\frame0")

OUTPUT_PATH3 = Path(__file__).parent
ASSETS_PATH3 = OUTPUT_PATH3 / Path(r"Page3.0\assets\frame0")

server_ip = '127.0.0.1'
server_port = 12345
client = EmailClient(server_ip, server_port)


def relative_to_assets1(path: str) -> Path:
    return ASSETS_PATH1 / Path(path)


def relative_to_assets2(path: str) -> Path:
    return ASSETS_PATH2 / Path(path)


def relative_to_assets3(path: str) -> Path:
    return ASSETS_PATH3 / Path(path)


window = Tk()


def base_page_gui():
    screen_width = window.winfo_screenwidth()
    screen_height = window.winfo_screenheight()

    x = (screen_width - 950) // 2
    y = (screen_height - 700) // 2

    window.geometry(f"950x700+{x}+{y}")

    window.configure(bg = "#FFFFFF")

    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 700,
        width = 950,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets1("image_1.png"))
    image_1 = canvas.create_image(
        475.0,
        350.0,
        image=image_image_1
    )

    canvas.create_text(
        304.0,
        65.0,
        anchor="nw",
        text="Email Sender",
        fill="#FFFFFF",
        font=("Inter", 55 * -1)
    )

    canvas.create_text(
        133.0,
        313.0,
        anchor="nw",
        text="Send",
        fill="#FFFFFF",
        font=("Inter", 55 * -1)
    )

    canvas.create_text(
        637.0,
        313.0,
        anchor="nw",
        text="Inbox",
        fill="#FFFFFF",
        font=("Inter", 55 * -1)
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets1("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: open_inbox_page(),
        relief="flat"
    )
    button_1.place(
        x=650.0,
        y=403.0,
        width=119.0,
        height=118.0
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets1("button_2.png"))

    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: open_composer_page(),
        relief="flat"
    )
    button_2.place(
        x=143.0,
        y=390.0,
        width=120.0,
        height=128.0
    )
    window.resizable(False, False)
    window.mainloop()
    return


def open_composer_page():  # Close the sender page
    composer_page_gui()  # Open the composer page


# Add a function to open the receiver page
def open_inbox_page(): # Close the sender page
    inbox_page_gui()  # Open the receiver page


def composer_page_gui():
    window.geometry("950x700")
    window.configure(bg="#927B70")

    canvas = Canvas(
        window,
        bg="#927B70",
        height=700,
        width=950,
        bd=0,
        highlightthickness=0,
        relief="ridge"
    )

    canvas.place(x=0, y=0)
    image_image_1 = PhotoImage(
        file=relative_to_assets2("image_1.png"))
    image_1 = canvas.create_image(
        475.0,
        377.0,
        image=image_image_1
    )

    canvas.create_rectangle(
        122.0,
        225.0,
        825.0,
        228.0,
        fill="#000000",
        outline="")

    canvas.create_text(
        125.0,
        181.0,
        anchor="nw",
        text="From:-",
        fill="#000000",
        font=("Inter", 30 * -1)
    )

    canvas.create_rectangle(
        122.0,
        327.0,
        825.0,
        330.0,
        fill="#000000",
        outline="")

    canvas.create_rectangle(
        122.0,
        586.0,
        831.0,
        589.0,
        fill="#000000",
        outline="")

    canvas.create_rectangle(
        122.0,
        274.0,
        825.0,
        277.0,
        fill="#000000",
        outline="")

    canvas.create_text(
        125.0,
        234.0,
        anchor="nw",
        text="To:-",
        fill="#000000",
        font=("Inter", 30 * -1)
    )

    canvas.create_text(
        125.0,
        286.0,
        anchor="nw",
        text="Subject:-",
        fill="#000000",
        font=("Inter", 30 * -1)
    )

    canvas.create_text(
        125.0,
        340.0,
        anchor="nw",
        text="Body:-",
        fill="#000000",
        font=("Inter", 30 * -1)
    )

    entry_image_1 = PhotoImage(
        file=relative_to_assets2("entry_3.png"))
    entry_bg_1 = canvas.create_image(
        520.5,
        201.0,
        image=entry_image_1
    )
    entry_1 = Entry(
        bd=0,
        bg="#DBCDC6",
        fg="#000716",
        highlightthickness=0,
        font=("Inter", 30 * -1)
    )
    entry_1.place(
        x=222.0,
        y=183.0,
        width=597.0,
        height=34.0
    )

    entry_image_2 = PhotoImage(
        file=relative_to_assets2("entry_2.png"))
    entry_bg_2 = canvas.create_image(
        541.0,
        303.0,
        image=entry_image_2
    )
    entry_2 = Entry(
        bd=0,
        bg="#DBCDC6",
        fg="#000716",
        highlightthickness=0,
        font=("Inter", 30 * -1)
    )
    entry_2.place(
        x=257.0,
        y=284.0,
        width=568.0,
        height=36.0
    )

    entry_image_3 = PhotoImage(
        file=relative_to_assets2("entry_1.png"))
    entry_bg_3 = canvas.create_image(
        508.0,
        252.0,
        image=entry_image_2
    )
    entry_3 = Entry(
        bd=0,
        bg="#DBCDC6",
        fg="#000716",
        highlightthickness=0,
        font=("Inter", 30 * -1)
    )
    entry_3.place(
        x=191.0,
        y=234.0,
        width=634.0,
        height=34.0
    )

    entry_image_4 = PhotoImage(
        file=relative_to_assets2("entry_4.png"))
    entry_bg_4 = canvas.create_image(
        475.0,
        479.5,
        image=entry_image_4
    )
    entry_4 = Text(
        bd=0,
        bg="#DBCDC6",
        fg="#000716",
        highlightthickness=0,
        font=("Inter", 20 * -1)
    )
    entry_4.place(
        x=125.0,
        y=381.0,
        width=700.0,
        height=195.0
    )

    image_image_2 = PhotoImage(
        file=relative_to_assets2("image_2.png"))
    image_2 = canvas.create_image(
        475.0,
        68.0,
        image=image_image_2
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets2("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: send_email_from_gui(entry_1, entry_2, entry_3, entry_4),
        relief="flat"
    )
    button_1.place(
        x=693.0,
        y=630.0,
        width=217.0,
        height=64.0
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets2("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: go_back_to_sender_page(),
        relief="flat"
    )
    button_2.place(
        x=15.0,
        y=16.0,
        width=78.0,
        height=68.0
    )
    window.resizable(False, False)
    window.mainloop()
    return entry_1,entry_2,entry_3,entry_4


def send_email_from_gui(entry_1, entry_2, entry_3, entry_4):
    sender = entry_1.get()
    recipient = entry_3.get()
    subject = entry_2.get()
    body = entry_4.get("1.0", "end-1c")
    if sender and recipient and subject and body:
        client.send_email(sender, recipient, subject, body)
        messagebox.showinfo("Email Sent", "Your email has been sent!")
        base_page_gui()

    else:
        messagebox.showerror("Error", "Please fill in all fields.")


def inbox_page_gui():
    window.geometry("950x700")
    window.configure(bg="#927B70")

    canvas = Canvas(
        window,
        bg="#927B70",
        height=700,
        width=950,
        bd=0,
        highlightthickness=0,
        relief="ridge"
    )

    canvas.place(x=0, y=0)
    image_image_1 = PhotoImage(
        file=relative_to_assets3("image_1.png"))
    image_1 = canvas.create_image(
        476.0,
        171.0,
        image=image_image_1
    )

    canvas.create_rectangle(
        122.0,
        191.0,
        826.0,
        194.0,
        fill="#000000",
        outline="")

    canvas.create_text(
        124.0,
        151.0,
        anchor="nw",
        text="Email:-",
        fill="#000000",
        font=("Inter", 30 * -1)
    )

    entry_image_1 = PhotoImage(
        file=relative_to_assets3("entry_1.png"))
    entry_bg_1 = canvas.create_image(
        506.0,
        169.0,
        image=entry_image_1
    )
    entry_1 = Entry(
        bd=0,
        bg="#DBCDC6",
        fg="#000716",
        highlightthickness=0,
        font=("Inter", 30 * -1)
    )
    entry_1.place(
        x=224.0,
        y=149.0,
        width=564.0,
        height=38.0
    )

    image_image_2 = PhotoImage(
        file=relative_to_assets3("image_2.png"))
    image_2 = canvas.create_image(
        474.0,
        467.0,
        image=image_image_2
    )

    canvas.create_rectangle(
        122.0,
        632.0,
        827.0,
        635.0,
        fill="#000000",
        outline="")

    entry_image_2 = PhotoImage(
        file=relative_to_assets3("entry_2.png"))
    entry_bg_2 = canvas.create_image(
        475.5,
        462.0,
        image=entry_image_2
    )
    entry_2 = Text(
        bd=0,
        bg="#DBCDC6",
        fg="#000716",
        highlightthickness=0,
        font=("Inter", 20 * -1)
    )
    entry_2.place(
        x=92.0,
        y=304.0,
        width=767.0,
        height=314.0
    )

    image_image_3 = PhotoImage(
        file=relative_to_assets3("image_3.png"))
    image_3 = canvas.create_image(
        475.0,
        67.0,
        image=image_image_3
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets3("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: send_recv_email_from_gui(entry_1, entry_2),
        relief="flat"
    )
    button_1.place(
        x=70.0,
        y=216.0,
        width=160.0,
        height=49.0
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets3("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: go_back_to_sender_page(),
        relief="flat"
    )
    button_2.place(
        x=22.0,
        y=21.0,
        width=78.0,
        height=68.0
    )
    window.resizable(False, False)
    window.mainloop()


def send_recv_email_from_gui(entry_1, entry_2):
    recipient = entry_1.get()
    entry_2.delete(1.0, "end")
    if recipient:
        emails = client.receive_email(recipient)
        for index, email in enumerate(emails, start=1):
            entry_2.insert("end", f"\n{index}) :\n")
            entry_2.insert("end", f"Date: {email['Date']}\n")
            entry_2.insert("end", f"Time: {email['Time']}\n")
            entry_2.insert("end", f"Sender: {email['Sender']}\n")
            entry_2.insert("end", f"Subject: {email['Subject']}\n")
            entry_2.insert("end", f"Body: {email['Body']}\n\n")

    else:
        messagebox.showerror("Error", "Enter your Mail!!!")


# Add a function to go back to the sender page
def go_back_to_sender_page(): # Close the receiver page
    base_page_gui()  # Open the sender page


# if __name__ == "__main__":

